language: node_js
dist: xenial
sudo: required

# ########################
# How to trigger a release
#
# Push a tag to origin:
# - "release" (= patch)
# - "release/patch"
# - "release/minor"
# - "release/major"
# ########################

stages:
  - name: release
    if: tag =~ /^release\/(major|minor|patch)$/

jobs:
  include:
    # Deploy stage
    # - code below is common between DAppNode packages
    ##################################################
    - stage: release
    name: release
    services:
      - docker
    node_js:
      - "10.15.3"
    deploy:
      provider: script
      script: npx dappnodesdk publish --dappnode_team_preset
      on:
        tags: true
        condition: "$TRAVIS_TAG = release || $TRAVIS_TAG = release/patch || $TRAVIS_TAG = release/minor || $TRAVIS_TAG = release/major"

